[package]
name = "physics"
version = "0.1.0"
authors = ["Fenimore Love <exorable.ludos@gmail.com>"]

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
find_folder = "0.3.0"
vecmath = "0.3.0"
rand = "0.3.14"
csv = "1.0.0"
